### ISSUE TITLE
Can not import the library

### ISSUE THREAD

**Issue by PierreRAFFA** [suguru/Cheetah#6]
Hi guys,
I am using Carthage to import your library but I received this message:
*** Checking out Cheetah at "0.2.6"
*** xcodebuild output can be found in /var/folders/d7/tmh15dlx1fj4vqz0sqwrk6knmz_k04/T/carthage-xcodebuild.TasAd5.log
xcodebuild timed out while trying to read CheetahExample.xcodeproj 😭
And nothing was imported in Build/tvOS folder
Any idea ?

**Comment by honghaoli** [comment]
same here

**Comment by HAKASHUN** [comment]
The latest master branch includes [this fix](https://github.com/suguru/Cheetah/commit/b21842cfedb2f3d392b387ba83493fdb3d1d33ae).

Please release a new version. 🙏 

Currently, I import this library by specifing master branch or the commit.

```
// Cartfile
github "suguru/Cheetah" "b21842cfedb2f3d392b387ba83493fdb3d1d33ae"
```
```
// Cartfile
github "suguru/Cheetah" "master"
```

**Comment by HAKASHUN** [comment]
I confirmed that there was no problem on this issue. Thanks!

**Comment by suguru** [comment]
I pushed 0.3.0 to trunk, so this issue can be closed
